# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
orbs:
   browser-tools: circleci/browser-tools@1.2.3
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
   codecov: codecov/codecov@3.2.2
jobs:
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
   build-and-test:
# These next lines define a Docker executor: https://circleci.com/docs/2.0/executor-types/
      docker:
      -  image: cimg/openjdk:11.0.17
# You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
      steps:
      - checkout
# Be sure to update the Docker image tag below to openjdk version of your application.
      -  run: java --version
#- run: mvn site
# A list of available CircleCI Docker Convenience Images are available here: https://circleci.com/developer/images/image/cimg/openjdk
# Add steps to the job
      -  run: mvn clean test
#- run: pwd
      -  run: mvn verify
      -  store_artifacts:
#- run: ls
            path: target/site
      - codecov/upload
# Then run your tests!s image is designed to supercede the l
   docs-build:
      docker:
      -  image: ubuntu-latest
      steps:
      -  name: Checkout code
         uses: actions/checkout@v2
# These next lines define a Docker executor: https://circleci.com/docs/2.0/executor-types/
      -  name: Build documentation
         run: mvn javadoc:javadoc
# You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
      -  name: Deploy documentation
         uses: peaceiris/actions-gh-pages@v3
# Be sure to update the Docker image tag below to openjdk version of your application.
# A list of available CircleCI Docker Convenience Images are available here: https://circleci.com/developer/images/image/cimg/openjdk
# Add steps to the job
         with:
#- run: mvn site
            github_token: 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
#- run: pwd
            publish_dir: ./docs
   docs-deploy:
      docker:
      -  image: node:8.10.0
      steps:
      - checkout
      -  attach_workspace:
            at: docs/_build
      -  run:
            name: Install and configure dependencies
            command: |
               npm install -g --silent gh-pages@2.0.1
               git config user.email "renoux.maxime@ntymail.com"
               git config user.name "MaximeRenoux"
      -  run:
            name: Deploy docs to gh-pages branch
            command: gh-pages --dist docs/_build/html
      -  add_ssh_keys:
            fingerprints:
            - SHA256:oJDIa5IFz+mIcKJyku6Y+Q+kRUPrIpPgclr9Mpms+p4
# Invoke jobs via workflows
workflows:
   sample: # This is the name of the workflow, feel free to change it to better match your workflow.
      jobs:
      - build-and-test
# Inside the workflow, you define the jobs you want to run.
      -  docs-deploy:
            requires:
# Below is the definition of your job to build and test your app, you can rename and customize it as you want.
            - test
            - docs-build
#Branche master uniquement
only:

- master